spring.application.name=backend
spring.mongodb.uri=mongodb+srv://javaswingdeveloper_db_user:AZYGPLnJLHuzOKex@projectlycluster0.ikzvzeb.mongodb.net/?appName=ProjectlyCluster0
spring.mongodb.database=projectly
server.port=9090

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.groups-order=DESC
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.show-actuator=false

resend.api.key=re_K1PHnf9N_4jsZ9y9A3168uv1ADe9XnWaW
app.reminder.email=java.swing.developer@gmail.com
